# Generated by Django 4.2.7 on 2024-04-23 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=120, unique=True)),
                ('lastname', models.CharField(max_length=120, unique=True)),
                ('phonenumber', models.CharField(max_length=20, unique=True)),
                ('birthday', models.DateField()),
                ('password', models.CharField(max_length=240)),
                ('email', models.CharField(max_length=120, unique=True)),
            ],
        ),
    ]
