# Generated by Django 5.0.4 on 2024-05-03 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authSec', '0005_types_competitions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Competitions',
        ),
    ]
