# Generated by Django 5.0.4 on 2024-05-03 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authSec', '0008_alter_temp_name_competitions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
