# Generated by Django 5.0.4 on 2024-05-05 08:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authSec', '0009_delete_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitions',
            name='uploadeddate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('commenteddate', models.DateField(default=django.utils.timezone.now)),
                ('commenteduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authSec.competitions')),
            ],
        ),
    ]
