# Generated by Django 5.0.4 on 2024-05-06 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authSec', '0010_competitions_uploadeddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='downvote',
            field=models.ManyToManyField(related_name='downvotedcomments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='upvote',
            field=models.ManyToManyField(related_name='upvotedcomments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competitions',
            name='delta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competitions',
            name='downvote',
            field=models.ManyToManyField(related_name='downvotedcompetitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competitions',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='competitions',
            name='upvote',
            field=models.ManyToManyField(related_name='upvotedcompetitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='comments',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='authSec.competitions'),
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('bio', models.CharField(default='', max_length=100)),
                ('registeredcompetitions', models.ManyToManyField(to='authSec.competitions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
