# Generated by Django 5.0.4 on 2024-05-07 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authSec', '0012_alter_profiles_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commenteduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='downvote',
            field=models.ManyToManyField(default=[], related_name='downvotedcomments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='upvote',
            field=models.ManyToManyField(default=[], related_name='upvotedcomments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='downvote',
            field=models.ManyToManyField(default=[], related_name='downvotedcompetitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='type',
            field=models.ManyToManyField(related_name='competitions', to='authSec.types'),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='upvote',
            field=models.ManyToManyField(default=[], related_name='upvotedcompetitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='registeredcompetitions',
            field=models.ManyToManyField(related_name='profiles', to='authSec.competitions'),
        ),
    ]
