# Generated by Django 5.0.4 on 2024-05-07 03:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authSec', '0013_alter_comments_commenteduser_alter_comments_downvote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='downvotedcomments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comments',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='upvotedcomments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='downvotedcompetitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='competitions',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='upvotedcompetitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
