# Generated by Django 5.0.4 on 2024-05-09 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authSec', '0015_alter_competitions_file_alter_profiles_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='commenteduser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
