# Generated by Django 5.0.4 on 2024-05-09 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authSec', '0016_alter_comments_commenteduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitions',
            name='organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
