# Generated by Django 5.0.4 on 2024-05-10 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authSec', '0021_profiles'),
    ]

    operations = [
    ]
